services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openresty
    image: machsgut/openresty-acme:latest
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./ssl/:/usr/local/openresty/ssl/
      - ./logs/:/usr/local/openresty/nginx/logs
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf.d/:/usr/local/openresty/nginx/conf.d/:ro
